### ISSUE TITLE
about the supplementary material of article MSMD-Net

### ISSUE THREAD

**Issue by ZhangYY12345** [gallenszl/PCWNet#4]
I am reading your article named _MSMD-Net: Deep Stereo Matching with Multi-scale and Multi-dimension Cost Volume_ recently. 

The thing is that you have mentioned **the supplementary material** in the article for detail reading, while I failed to find them from the Internet. Would you please send me an email copy of the supplementary meterial? The email address is _annazyybrave@gmail.com_

Many Thanks

**Comment by gallenszl** [comment]
sorry fot the late reply. code is open-sourced and please see our final accepted version pcwnet for more details.
